name: ci

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
       name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./dotnet-docker/src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-docker:v1
